old_sound_rabbit_mq:
    connections:
        default:
#            url: '%env(RABBITMQ_URL)%'
            host: 'rabbitmq' # todo can be moved to env
            port: 5672
            user: 'tt-user'
            password: 'tt-pass'
#    producers:
#        # use 'old_sound_rabbit_mq.task_producer' service to send data.
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
#    consumers:
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
#            queue_options:    { name: 'task'}
#            callback:         App\Consumer\TaskConsumer
